jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # ✅ REQUIRED for Azure OIDC login
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92423B9CA59A4251AFD9E96E6C6CD837 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E67A8EF5E68F4630A647E78BD98A10AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_07A9D4E73251462A8F8F30CCDA7DFAF6 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'resume-filter'
          slot-name: 'Production'
          package: '.'
